### ISSUE TITLE
Vẽ giao diện đăng ký học [BA]

### ISSUE THREAD

**Issue by vnkhoa02** [vnkhoa02/harvard-tay-son#17]
- Vẽ sơ qua, giống với nhà trường

**Comment by hhmai1881** [comment]
![form_CNPM2](https://user-images.githubusercontent.com/90233663/155996136-42be8596-3ed9-4daf-8b75-62a4c17792cd.png)

**Comment by hhmai1881** [comment]
![image](https://user-images.githubusercontent.com/90233663/157266097-7de072d1-a17b-4f9c-a210-3aa4582ba140.png)
giao diện đăng ký + tìm kiếm môn học

**Comment by hhmai1881** [comment]
![image](https://user-images.githubusercontent.com/90233663/157266222-8ff9357b-63ae-419d-94b0-334d334f8a81.png)
giao diện hủy môn học
