### ISSUE TITLE
Vẽ giao diện thông tin cá nhân [BA]

### ISSUE THREAD

**Issue by vnkhoa02** [vnkhoa02/harvard-tay-son#24]
vẽ sơ cua, giống với nhà tr

**Comment by hhmai1881** [comment]
![form_TTCN](https://user-images.githubusercontent.com/90233663/156907005-3d47759b-00a0-4d57-8152-6ad5cae7f91c.png)

**Comment by hhmai1881** [comment]
![image](https://user-images.githubusercontent.com/90233663/157265800-094bee06-0cba-4011-b79f-224e47f99439.png)
